repos:
-   repo: https://github.com/mwouts/jupytext
    rev: v1.14.7  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--pipe, black]
      exclude: runbook/data/_template-deno.ipynb|.*\.md|tests/.*
      additional_dependencies:
        - black==23.3.0 # Matches hook

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "d7f0995" # 2025-02-07
  hooks:
    - id: ruff
      args: [--fix]
      exclude: runbooks/binder/_template-deno.ipynb
    - id: ruff-format
      exclude: runbooks/binder/_template-deno.ipynb

-   repo: local
    hooks:
    -   id: tests
        name: Runs tests
        entry: just test
        language: system
        files: '.*$'
        pass_filenames: false
#     -   id: update-readme
#         name: Runs readme templating
#         entry: just readme
#         language: system
#         files: '.*$'
#         pass_filenames: false
