[project]
name = "runbook"
version = "0"
description = "Runbook lib and cli"
requires-python = ">=3.11"
authors = [
  { name = "Zander Hill", email = "zander@xargs.io" },
]
license = "MIT"
readme = "README.md"
dependencies = [
    "shx>=0.4.2",
    "rich>=13.9.4",
    "papermill @ git+https://github.com/zph/papermill@main",
    "jupyter>=1.0.0",
    "click>=8.1.7",
    "bash-kernel>=0.9.3",
    "jupyterlab-execute-time>=3.1.0",
    "jupytext==1.16.6",
    "nbformat>=5.9.2",
    "pyyaml>=6.0.1",
    "traitlets>=5.14.1",
    "ipywidgets>=8.1.1",
    "pre-commit>=3.6.0",
    "python-ulid>=2.2.0",
    "slack-sdk>=3.26.2",
    "jupyterlab>=4.1.5",
    "nbdime>=4.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.9.5",
]

[project.scripts]
runbook = "runbook.cli:cli"
# For the sake of installation accessibility for deno notebooks
jupyter = "jupyter_core.command:main"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:jupyter_client.connect",
    "ignore::DeprecationWarning:papermill.parameterize",
]

[tool.ruff]
line-length = 88  # Same default as Black (adjust if needed)

[tool.ruff.format]
quote-style = "double"  # Choose "single" or "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
select = ["I"]
